version: '3.7'
services:
  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: personifydev
      MONGO_INITDB_ROOT_PASSWORD: testenv@123
    command: [ --auth ]
    ports:
      - 27017:27017
    networks:
      - personify-dev-net
  db-admin:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongodb
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: personifydev
      ME_CONFIG_MONGODB_ADMINPASSWORD: testenv%40123
      ME_CONFIG_MONGODB_SERVER: mongodb
    networks:
      - personify-dev-net
networks:
  personify-dev-net:
    driver: bridge
