version: '3.8'
services:
  personify-service:
    image: personify-service
    build:
      context: .
      dockerfile: ./Dockerfile.prod
    expose:
      - 8888
    networks:
      - personify-net
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - personify-service
    networks:
      - personify-net
networks:
  personify-net:
    driver: bridge
