[mypy]
; Import Discovery
; explicit_package_bases = False
; namespace_packages = False
; ignore_missing_imports = True
; follow_imports = normal
; follow_imports_for_stubs = False
; no_site_packages = False
; no_silence_site_packages = False

; Platform configuration
; python_version = 3.8
; platform = linux

; Disallow dynamic typing
; disallow_any_unimported = False
; disallow_any_expr = False
; disallow_any_decorated = False
; disallow_any_explicit = False
; disallow_any_generics = False

; Untyped definitions and calls
; disallow_untyped_calls = False
; disallow_untyped_defs = False
; disallow_incomplete_defs = False
; check_untyped_defs = True
; disallow_untyped_decorators = False

; None and Optional handling
; implicit_optional = False
; strict_optional = False

; Configuring warnings
; warn_redundant_casts = False
; warn_unused_ignores = False
; warn_no_return = False
; warn_return_any = True
; warn_unreachable = False

; Suppressing errors
; ignore_errors = False

; Miscellaneous strictness flags
; allow_untyped_globals = False
; allow_redefinition = False
; local_partial_types = False
; implicit_reexport = True
; strict_concatenate = False
; strict_equality = False
; strict = True

; Configuring error messages
; show_error_context = False
; show_column_numbers = False
; hide_error_codes = False
; pretty = False
; color_output = True
; error_summary = True
; show_absolute_path = False
; force_uppercase_builtins = True
; force_union_syntax = False


; Incremental mode
; incremental = True
; cache_dir = .mypy_cache
; sqlite_cache = False
; cache_fine_grained = False
; skip_version_check = False
; skip_cache_mtime_checks = False

; Advanced options
; pdb = False
; show_traceback = True
; raise_exceptions = True
; warn_incomplete_stub = False

; Report generation

; Miscellaneous
; scripts_are_modules = False
; warn_unused_configs = True
; verbosity = 1
