  version: 1
  formatters:
    brief:
      format: "%(asctime)s %(name)s %(levelname)s : %(message)s"
    detailed:
      format: 'time="%(asctime)s" logger="%(name)s" level="%(levelname)s" file="%(filename)s" lineno=%(lineno)d function="%(funcName)s" %(message)s'
  handlers:
    console:
      class: logging.StreamHandler
      level: INFO
      formatter: brief
      stream: ext://sys.stdout
    file:
      class: logging.handlers.RotatingFileHandler
      level: DEBUG
      formatter: detailed
      filename: /tmp/customers-service-app.log
      backupCount: 3
  loggers:
    alembic:
      level: INFO
      handlers:
        - console
        - file
      qualname: alembic
      propagate: no
    sqlalchemy.engine.Engine:
      level: WARNING
      handlers:
        - console
        - file
      qualname: sqlalchemy.engine.Engine
      propagate: no
    personify-service:
      level: DEBUG
      handlers:
        - console
        - file
      propagate: no
    tornado.access:
      level: DEBUG
      handlers:
        - file
    tornado.application:
      level: DEBUG
      handlers:
        - file
    tornado.general:
      level: DEBUG
      handlers:
        - file
  root:
    level: WARNING
    handlers:
      - console
