name: Pytest

on: [push]
jobs:
  run_pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Display Python Version
        run: python -c "import sys; print(sys.version)"
      - name: Updrade Pip
        run: python -m pip install --upgrade pip
      - name: Install Package Locally
        run: python -m pip install .
      - name: Install required packages along with Pytest
        run: pip install pytest pytest-cov pytest-asyncio
      - name: Running tests with Code Coverage
        run: pytest -vv --junitxml=coverage.xml --cov --cov-report=term-missing