name: Ruff

on: [push]

jobs:
  apply_ruff:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Display Python Version
        run: python -c "import sys; print(sys.version)"
      - name: Updrade Pip
        run: python -m pip install --upgrade pip
      - name: Install Ruff
        run: pip install ruff
      - name: Analysing the code with Ruff
        run: ruff check .